export const DEFAULT_WAB_URL = 'noWAB'
export const DEFAULT_STORAGE_URL = 'local'
export const DEFAULT_MESSAGEBOX_URL = 'noMessageBox'
export const DEFAULT_CHAIN = 'main'
export const ADMIN_ORIGINATOR = 'admin.com'
