#!/usr/bin/env python3
"""Record the dependency Cargo actually resolved; fail on missing provenance."""
import json
import pathlib
import re
import sys

metadata = json.load(sys.stdin)
packages = [p for p in metadata['packages'] if p['name'] == 'bsv-rs']
if len(packages) != 1:
    raise SystemExit('Expected exactly one resolved bsv-rs package')
package = packages[0]
if package['version'] != '0.3.18' or not package['source'].startswith('registry+'):
    raise SystemExit('Expected the pinned bsv-rs registry package')
lock = pathlib.Path(sys.argv[1]).read_text()
blocks = [b for b in lock.split('[[package]]') if re.search(r'^name = "bsv-rs"$', b, re.M)]
if len(blocks) != 1:
    raise SystemExit('Expected exactly one locked bsv-rs package')
checksum = re.search(r'^checksum = "([a-f0-9]{64})"$', blocks[0], re.M)
if not checksum:
    raise SystemExit('Missing locked bsv-rs registry checksum')
vcs_path = pathlib.Path(package['manifest_path']).parent / '.cargo_vcs_info.json'
commit = json.loads(vcs_path.read_text())['git']['sha1']
if not re.fullmatch(r'[a-f0-9]{40}', commit):
    raise SystemExit('Missing published source commit')
pathlib.Path(sys.argv[2]).write_text(
    '# BSV-RS-PIN — locked registry dependency\n\n'
    'Generated by `scripts/record-engine-dependency.py` from locked Cargo metadata,\n'
    '`Cargo.lock`, and the registry package\'s `.cargo_vcs_info.json`.\n'
    'The registry checksum pins the downloaded source; no sibling checkout is used.\n\n'
    f'- Package: `bsv-rs {package["version"]}`\n'
    f'- Source: `{package["source"]}`\n'
    f'- Registry checksum: `{checksum.group(1)}`\n'
    f'- Published source commit: `{commit}`\n'
)
